import React from "react";
import { useNavigate } from "react-router-dom";
import logo from "../assets/logo.png";

export default function Terms() {
  const navigate = useNavigate();

  const handlePrint = () => {
    window.print();
  };
return (
  <div className="min-h-screen bg-[#FDFCFB] px-6 py-16 lg:py-24 font-['Sora'] text-[#2D2D2D] selection:bg-[#F2F8FF]">
    <div className="max-w-2xl mx-auto">
      
      {/* Header - Centered & Soft */}
      <header className="mb-20 text-center">
        <div className="flex justify-center mb-8">
          <img
            src={logo}
            alt="Clear Clause"
            className="h-9 w-auto opacity-90 hover:opacity-100 transition-opacity cursor-pointer"
            onClick={() => navigate("/")}
          />
        </div>

        <h1 className="text-3xl font-['Sora'] lg:text-4xl font-bold tracking-tight text-[#1A1A1A] mb-4">
          Terms of Service
        </h1>

        <div className="flex items-center justify-center gap-3">
          <span className="h-px w-8 bg-gray-200"></span>
          <p className="text-[13px] font-['Sora'] font-medium text-gray-400 uppercase tracking-widest">
            February 1, 2026
          </p>
          <span className="h-px w-8 bg-gray-200"></span>
        </div>
      </header>

      {/* Content - Spacious & Readable */}
      <main className="space-y-12 text-[15px] leading-[1.8] text-[#4A4A4A]">
        
        <section className="relative">
          <h2 className="text-[17px] font-['Sora'] font-bold text-[#1A1A1A] mb-3">
            1. Acceptance of Terms
          </h2>
          <p className="font-['Sora']">
            By accessing or using <span className="text-black font-semibold">Clear Clause</span>, you agree to be
            bound by these Terms of Service. Clear Clause provides AI-generated
            analysis of legal documents strictly for <span className="italic">informational and educational purposes</span>.
          </p>
        </section>

        <section className="bg-[#FFF9F5] p-8 rounded-[2rem] border border-[#F5EBE4]">
          <h2 className="text-[17px] font-['Sora'] font-bold text-[#1A1A1A] mb-3">
            2. No Legal Advice
          </h2>
          <div className="space-y-4">
            <p>
              Clear Clause is not a law firm and does not provide legal advice.
              All outputs are generated by artificial intelligence and should not
              be relied upon as a substitute for professional legal counsel.
            </p>
            <p className="text-[#6B6B6B] font-['Sora']">
              No attorney-client relationship is created through use of the
              platform. You are solely responsible for how you interpret or use
              the information provided.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-[17px] font-['Sora'] font-bold text-[#1A1A1A] mb-3">
            3. Privacy & Data Processing
          </h2>
          <p className="font-['Sora']">
            Uploaded source files are removed after extraction. ClearClause stores extracted text and analysis for your account so you can review results and use Ask ClearClause. This information is not shared or used for model training. Your privacy is our baseline.
          </p>
        </section>

        <section>
          <h2 className="text-[17px] font-['Sora'] font-bold text-[#1A1A1A] mb-3">
            4. Limitation of Liability
          </h2>
          <p className="font-['Sora']">
            To the fullest extent permitted by law, Clear Clause shall not be
            liable for any direct, indirect, or consequential
            damages arising from your use of the service or reliance on its
            outputs, including classifications of clauses as “risky” or “secure.”
          </p>
        </section>

      </main>

      {/* Footer - Elegant & Minimal */}
      <footer className="mt-24 pt-12 border-t border-gray-100 text-center">
        <p className="text-[12px] font-['Sora'] text-gray-400 font-medium">
          © 2026 CLEAR CLAUSE AI. ALL RIGHTS RESERVED.
        </p>

        <button
          onClick={() => navigate(-1)}
          className="mt-10 group font-['Sora'] flex items-center gap-2 mx-auto text-sm font-bold text-[#1A1A1A] hover:text-[#0073FF] transition-colors"
        >
          <span className="group-hover:-translate-x-1 transition-transform">←</span>
          Return to register
        </button>
      </footer>

    </div>
  </div>
);
}
