import React from "react";
import { useNavigate } from "react-router-dom";
import logo from "../assets/logo.png";

export default function Terms() {
  const navigate = useNavigate();

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-[#F9F9F9] py-6 lg:py-12 px-4 font-['Sora']">
      <div className="max-w-3xl mx-auto bg-white rounded-[2rem] shadow-sm border border-gray-100 overflow-hidden print:shadow-none print:border-none print:rounded-none">
        {/* Header - Optimized for Mobile & Print */}
<div className="px-4 py-5 lg:px-8 lg:py-6 border-b border-gray-100 flex justify-between items-center bg-white/80 backdrop-blur-md sticky top-0 z-50 print:static print:border-none">
  
  {/* Logo Section */}
  <div className="flex items-center">
    <img 
      src={logo} 
      alt="Clear Clause" 
      className="h-7 lg:h-9 w-auto object-contain active:scale-95 transition-transform" 
    />
  </div>

  {/* Actions Section */}
  <div className="flex gap-3 lg:gap-6 items-center">
    {/* Print Button - Still hidden on mobile to save space, but styled better for desktop */}
    <button 
      onClick={handlePrint}
      className="hidden sm:flex items-center gap-2 font-['Sora'] text-gray-400 hover:text-[#0073FF] text-sm font-semibold transition-all"
    >
      <span className="text-lg">🖨️</span>
      Print Review
    </button>

    {/* Back Button - Bigger tap target for mobile */}
    <button 
      onClick={() => navigate(-1)}
      className="bg-[#F2F8FF] font-['Sora'] text-[#0073FF] px-5 py-2.5 lg:px-6 lg:py-3 rounded-2xl text-[13px] lg:text-sm font-bold active:scale-95 hover:bg-[#0073FF] hover:text-white transition-all shadow-sm shadow-blue-100"
    >
      Back
    </button>
  </div>
</div>

        <div className="p-8 lg:p-12">
          <header className="mb-10">
            <h1 className="text-2xl font-['Sora'] lg:text-3xl font-bold text-[#1A1A1A] mb-2">Terms and Services</h1>
            <p className="text-gray-400 font-['Sora'] text-xs lg:text-sm">Effective Date: February 1, 2026</p>
          </header>

          <div className="space-y-8 text-[#4D4D4D] leading-relaxed text-sm lg:text-[15px]">
            <section>
              <h2 className="text-lg font-['Sora'] font-bold text-[#0073FF] mb-3">1. Acceptance of Terms</h2>
              <p className="font-['Sora'] " >By accessing or using <strong>Clear Clause</strong>, you agree to be bound by these Terms. Our platform provides AI-driven analysis of legal documents for educational and informational purposes.</p>
            </section>

            <section className="bg-[#FFF9F2] p-6 rounded-2xl border-l-4 border-[#D4AF37]">
              <h2 className="text-lg font-bold font-['Sora'] text-[#D4AF37] mb-2">2. Not a Substitute for Legal Counsel</h2>
              <p className="text-sm font-['Sora'] font-medium text-[#7A6319]">
                Clear Clause is not a law firm. The analysis provided is generated by Artificial Intelligence and does not constitute legal advice. No attorney-client relationship is formed through the use of this tool. Always consult a licensed attorney for critical legal decisions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-['Sora'] font-bold text-[#0073FF] mb-3">3. Privacy and Data Handling</h2>
              <p className="font-['Sora'] " >We take your privacy seriously. Clear Clause operates on a <strong>non-storage policy</strong>. Documents uploaded for analysis are processed in real-time and are not saved, stored, or used for training models after your session concludes.</p>
            </section>

            <section>
              <h2 className="text-lg font-['Sora'] font-bold text-[#0073FF] mb-3">4. Limitation of Liability</h2>
              <p className="font-['Sora'] " >To the maximum extent permitted by law, Clear Clause shall not be liable for any damages resulting from the use or inability to use the service, including any reliance placed on the AI's detection of "risky" or "secure" clauses.</p>
            </section>
          </div>

          <footer className="mt-16 pt-8 border-t border-gray-50 text-center">
            <p className="text-xs font-['Sora'] text-gray-400 font-medium">
              &copy; 2026 Clear Clause AI. All rights reserved.
            </p>
          </footer>
        </div>
      </div>
    </div>
  );
}